### ISSUE TITLE
gz files do not work as input

### ISSUE THREAD

**Issue by c-mertes** [BennyStrobes/SPOT#3]
The gzipped cluster files from Leafcutter are not working with SPOT.

Using the [example file](https://github.com/BennyStrobes/SPOT/files/5017441/bugreport_input.counts.txt) from issue #2 we can reproduce the error like this:

 ```
cat bugreport_input.counts.txt | gzip -c > bugreport_input.counts.gz
file bugreport_input.counts.gz
# bugreport_input.counts.gz: gzip compressed data, from Unix, last modified: Mon Aug  3 19:46:29 2020
python3 ./spot.py -j bugreport_input.counts.gz -o bugreport
# Traceback (most recent call last):
#   File "./spot.py", line 197, in <module>
#     main(options)
#   File "./spot.py", line 162, in main
#     cluster_jxn_data_structure, sample_names = load_in_junction_count_data(junc_file, max_junctions)
#   File "./spot.py", line 78, in load_in_junction_count_data
#     cluster_jxn_data_structure, sample_names = extract_raw_cluster_jxn_data_structure(junc_file)
#   File "./spot.py", line 29, in extract_raw_cluster_jxn_data_structure
#     key_info = key.split(':')
# TypeError: a bytes-like object is required, not 'str'
```

**Comment by BennyStrobes** [comment]
Strange. I just ran the compressed version of your example file (`bugreport_input.counts.gz`) and it ran without issues. I see you are using python3. The code was developed and tested using python 2.7.15. So maybe try that? Was there no issues when you ran the uncompressed version.

**Comment by c-mertes** [comment]
I did a quick end to end test with the input counts and the results are the same (accounting for the randomness of the p-value). So the change should fix the issue to move to python 3.

some background: https://bugs.python.org/issue13989
